import { useTranslations } from '../i18n/utils';

function getMapRoutes(t: ReturnType<typeof useTranslations>) {
  return [
    {
      id: 'nightMarkets',
      name: t('map.routes.nightMarkets.name'),
      description: t('map.routes.nightMarkets.description'),
      color: '#f39c12',
      stops: [
        {
          id: 'shilinNightMarket',
          name: t('map.stops.shilinNightMarket.name'),
          lat: 25.088,
          lng: 121.524,
          note: t('map.stops.shilinNightMarket.note'),
          link: '/food/夜市文化',
        },
        {
          id: 'raoheNightMarket',
          name: t('map.stops.raoheNightMarket.name'),
          lat: 25.051,
          lng: 121.577,
          note: t('map.stops.raoheNightMarket.note'),
          link: '/food/夜市文化',
        },
        {
          id: 'ningxiaNightMarket',
          name: t('map.stops.ningxiaNightMarket.name'),
          lat: 25.056,
          lng: 121.515,
          note: t('map.stops.ningxiaNightMarket.note'),
          link: '/food/夜市文化',
        },
        {
          id: 'fengjiaNightMarket',
          name: t('map.stops.fengjiaNightMarket.name'),
          lat: 24.179,
          lng: 120.647,
          note: t('map.stops.fengjiaNightMarket.note'),
          link: '/food/夜市文化',
        },
        {
          id: 'huayuanNightMarket',
          name: t('map.stops.huayuanNightMarket.name'),
          lat: 23.004,
          lng: 120.206,
          note: t('map.stops.huayuanNightMarket.note'),
          link: '/food/夜市文化',
        },
        {
          id: 'liuheNightMarket',
          name: t('map.stops.liuheNightMarket.name'),
          lat: 22.632,
          lng: 120.299,
          note: t('map.stops.liuheNightMarket.note'),
          link: '/food/夜市文化',
        },
      ],
    },
    {
      id: 'nationalParks',
      name: t('map.routes.nationalParks.name'),
      description: t('map.routes.nationalParks.description'),
      color: '#27ae60',
      stops: [
        {
          id: 'yangmingshanNationalPark',
          name: t('map.stops.yangmingshanNationalPark.name'),
          lat: 25.158,
          lng: 121.549,
          note: t('map.stops.yangmingshanNationalPark.note'),
          link: '/nature/國家公園',
        },
        {
          id: 'tarokoNationalPark',
          name: t('map.stops.tarokoNationalPark.name'),
          lat: 24.158,
          lng: 121.621,
          note: t('map.stops.tarokoNationalPark.note'),
          link: '/nature/國家公園',
        },
        {
          id: 'yushanNationalPark',
          name: t('map.stops.yushanNationalPark.name'),
          lat: 23.47,
          lng: 120.957,
          note: t('map.stops.yushanNationalPark.note'),
          link: '/nature/國家公園',
        },
        {
          id: 'alishanScenicArea',
          name: t('map.stops.alishanScenicArea.name'),
          lat: 23.51,
          lng: 120.7,
          note: t('map.stops.alishanScenicArea.note'),
          link: '/nature/阿里山',
        },
        {
          id: 'sunMoonLakeScenicArea',
          name: t('map.stops.sunMoonLakeScenicArea.name'),
          lat: 23.863,
          lng: 120.917,
          note: t('map.stops.sunMoonLakeScenicArea.note'),
          link: '/nature/日月潭',
        },
        {
          id: 'kentingNationalPark',
          name: t('map.stops.kentingNationalPark.name'),
          lat: 21.948,
          lng: 120.803,
          note: t('map.stops.kentingNationalPark.note'),
          link: '/nature/國家公園',
        },
      ],
    },
    {
      id: 'historyTrail',
      name: t('map.routes.historyTrail.name'),
      description: t('map.routes.historyTrail.description'),
      color: '#e74c3c',
      stops: [
        {
          id: 'anpingFort',
          name: t('map.stops.anpingFort.name'),
          lat: 22.998,
          lng: 120.161,
          note: t('map.stops.anpingFort.note'),
          link: '/history/荷蘭與西班牙殖民時期',
        },
        {
          id: 'chikanTower',
          name: t('map.stops.chikanTower.name'),
          lat: 22.998,
          lng: 120.203,
          note: t('map.stops.chikanTower.note'),
          link: '/history/鄭氏時期',
        },
        {
          id: 'lukang',
          name: t('map.stops.lukang.name'),
          lat: 24.055,
          lng: 120.437,
          note: t('map.stops.lukang.note'),
          link: '/culture/鹿港',
        },
        {
          id: 'presidentialOffice',
          name: t('map.stops.presidentialOffice.name'),
          lat: 25.04,
          lng: 121.512,
          note: t('map.stops.presidentialOffice.note'),
          link: '/history/日本殖民統治',
        },
        {
          id: 'chiangKaiShekMemorialHall',
          name: t('map.stops.chiangKaiShekMemorialHall.name'),
          lat: 25.036,
          lng: 121.522,
          note: t('map.stops.chiangKaiShekMemorialHall.note'),
          link: '/history/戒嚴時期',
        },
        {
          id: 'legislativeYuan',
          name: t('map.stops.legislativeYuan.name'),
          lat: 25.044,
          lng: 121.521,
          note: t('map.stops.legislativeYuan.note'),
          link: '/society/太陽花學運',
        },
      ],
    },
    {
      id: 'oldStreets',
      name: t('map.routes.oldStreets.name'),
      description: t('map.routes.oldStreets.description'),
      color: '#9b59b6',
      stops: [
        {
          id: 'dihuaStreet',
          name: t('map.stops.dihuaStreet.name'),
          lat: 25.057,
          lng: 121.51,
          note: t('map.stops.dihuaStreet.note'),
          link: '/culture/大稻埕',
        },
        {
          id: 'jiufenOldStreet',
          name: t('map.stops.jiufenOldStreet.name'),
          lat: 25.109,
          lng: 121.845,
          note: t('map.stops.jiufenOldStreet.note'),
          link: '/culture/九份',
        },
        {
          id: 'lukangOldStreet',
          name: t('map.stops.lukangOldStreet.name'),
          lat: 24.055,
          lng: 120.437,
          note: t('map.stops.lukangOldStreet.note'),
          link: '/culture/鹿港',
        },
        {
          id: 'anpingOldStreet',
          name: t('map.stops.anpingOldStreet.name'),
          lat: 22.998,
          lng: 120.161,
          note: t('map.stops.anpingOldStreet.note'),
          link: '/history/安平',
        },
        {
          id: 'qishanOldStreet',
          name: t('map.stops.qishanOldStreet.name'),
          lat: 22.889,
          lng: 120.483,
          note: t('map.stops.qishanOldStreet.note'),
          link: '/culture/旗山',
        },
        {
          id: 'tamsuiOldStreet',
          name: t('map.stops.tamsuiOldStreet.name'),
          lat: 25.17,
          lng: 121.44,
          note: t('map.stops.tamsuiOldStreet.note'),
          link: '/culture/淡水',
        },
      ],
    },
  ];
}
